### ISSUE TITLE
Php auto load faild

### ISSUE THREAD

**Issue by amirrezagh75** [yovanoc/marketplace#2]
Can't run " php artisan key:generate " because of the missing vendor folder

**Comment by yovanoc** [comment]
Oh yeah you are right you have to composer install before I will add this in the readme !

**Comment by amirrezagh75** [comment]
when I request for installing composer I got these errors!!

  Problem 1
    - Installation request for pusher/pusher-php-server 3.0.0 -> satisfiable by pusher/pusher-php-server[3.0.0].
    - pusher/pusher-php-server 3.0.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 2
    - Installation request for stripe/stripe-php v5.1.2 -> satisfiable by stripe/stripe-php[v5.1.2].
    - stripe/stripe-php v5.1.2 requires ext-curl * -> the requested PHP extension curl is missing from your system.

**Comment by yovanoc** [comment]
You need to enable curl in your php installation

**Comment by amirrezagh75** [comment]
Yeah, you are right!! after enabling curl in php.ini my problem been solved!! thanks!

**Comment by yovanoc** [comment]
Nice! :+1:
